### ISSUE TITLE
add support for non-uniformity correction

### ISSUE THREAD

**Issue by lunebellec** [SIMEXP/niak#398]
this would be based on AFNI.

# TODO
 - [ ] update niak docker container to add afni. 
 - [ ] create bricks for distortion correction
 - [ ] run tests
 - [ ] add brick to the preprocessing pipeline

# Resources: 
[Example of docker file for AFNI](https://github.com/BIDS-Apps/afni_proc/blob/master/Dockerfile)
[nipype interfaces](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.afni.preprocess.html) for Qwarp and QwarpPlusMinus.
